### ISSUE TITLE
个人小建议：

### ISSUE THREAD

**Issue by XStrm** [lich0821/wcf-client-rust#1]
个人小建议：
输入回调接口地址 会把接收到的消息等事件提交给这个接口

新增 一个接口地址，软件轮询该地址，该地址返回指定格式的内容然后由软件主动发送消息或者处理

**Comment by lich0821** [comment]
谢谢建议，不过没理解需求😅

**Comment by goooooooooog** [comment]
这应该是老年间机器人的一个功能了，提主，应该是老年间的机器人使用者吧。

翻译一下：机器人维持一个心跳，每隔10秒去GET一个地址，地址返回命令给机器人，机器人按照命令去执行动作。比如发送消息。

这个功能是没有必要的。自己可以去维护一个心跳，往接口POST数据，不是更灵活更方便嘛。

**Comment by lich0821** [comment]
完蛋，你翻译完我还是没看懂……脑子不在了。

**Comment by lich0821** [comment]
推拉我理解了。如果要拉的话，收到消息得先有个地方“存”，存哪里呢？

**Comment by goooooooooog** [comment]
推不是推到一个URL嘛，拉也定义一个URL不就有了嘛。

**Comment by goooooooooog** [comment]
数据库，

**Comment by lich0821** [comment]
数据库本来就有了，直接查就好了

**Comment by XStrm** [comment]
是的，现在没有“拉”，只能推，电脑得做端口转发才行，因为没有公网

**Comment by goooooooooog** [comment]
> 是的，现在没有“拉”，只能推，电脑得做端口转发才行，因为没有公网

那就自己在电脑上维护一个拉进程 拉到数据了 推到微信上

这不是什么问题
