### ISSUE TITLE
接口发送出去的消息怎么才能拿到？

### ISSUE THREAD

**Issue by lyx102** [lich0821/wcf-client-rust#24]
rust客户端终端输出没有，手机自己发的可以看到，但是接口发出去的看不到

**Comment by lich0821** [comment]
[我自己发送给别人的消息，程序里面为啥收不到啊？](https://github.com/lich0821/WeChatFerry/issues/34)

[希望作者可以增加拦截pc发消息的功能](https://github.com/lich0821/WeChatFerry/issues/45)
