### ISSUE TITLE
大佬，如何获取群成员昵称

### ISSUE THREAD

**Issue by knight-666** [lich0821/wcf-client-rust#34]
目前通过查询库，只能查询到群成员的wxid，无法获取昵称

![image](https://github.com/user-attachments/assets/e296715e-8d3f-4104-8909-140493f218b4)

RoomData解析出来的数据为

![image](https://github.com/user-attachments/assets/928a1447-c961-4d79-93b0-c7ec02d0f508)

**Comment by lich0821** [comment]
@supermoonie 大佬～

**Comment by supermoonie** [comment]
> @supermoonie 大佬，这接口我怎么记得好像加过

加过了

**Comment by knight-666** [comment]
> @supermoonie 大佬，这接口我怎么记得好像加过

不好意思，才发现都更新两个版本了，我还用的 39.2.4.0 ，新版确实有了，感谢大佬

**Comment by knight-666** [comment]
![image](https://github.com/user-attachments/assets/98ab762d-d751-48bc-8df4-d4c9d8543cdf)
还是获取不到群成员昵称，wcfrust版本更新到了39.2.4.2

看了下这个项目https://github.dev/LC044/WeChatMsg/，个人猜测这个群成员昵称估计得从 ChatRoomUser.db 库里面获取
![image](https://github.com/user-attachments/assets/dadad164-7d5b-408c-a855-3b578f1a858e)

**Comment by supermoonie** [comment]
@knight-666 这个我遇到过，你说的那个表我之前查过，也没名字，微信多登录几次就有了，很奇怪的逻辑，这几天我优化下这个接口

**Comment by supermoonie** [comment]
@lich0821 ChatRoomUser.db 有这个数据库吗

**Comment by lich0821** [comment]
> @lich0821 ChatRoomUser.db 有这个数据库吗

没注意到
