### ISSUE TITLE
撤回消息失败

### ISSUE THREAD

**Issue by Jxells** [lich0821/wcf-client-rust#35]
调用撤回消息的接口无法撤回消息
![image](https://github.com/user-attachments/assets/95af4c9d-5f97-4c89-a2b3-5b835d65ad7f)

**Comment by lich0821** [comment]
https://github.com/lich0821/WeChatFerry/issues/196#issuecomment-2269332651

**Comment by isqyz** [comment]
撤回功能删除了吗

**Comment by isqyz** [comment]
> [lich0821/WeChatFerry#196 (评论)](https://github.com/lich0821/WeChatFerry/issues/196#issuecomment-2269332651)

请问撤回功能删除了吗
