### ISSUE TITLE
【建议】客户端exe的小建议

### ISSUE THREAD

**Issue by PathfinderAx** [lich0821/wcf-client-rust#36]
1.希望界面能够自定义拖动大小
2.希望客户端界面支持多个回调地址
3.希望文档中增加动态添加回调地址的接口
4.希望在有回调地址的情况下，客户端接口有开关控制客户端是否输出消息内容(目前是回调地址打印，客户端界面就不在打印输出消息内容了)
5.界面支持查看当前版本

当前版本：v39.2.4.2

**Comment by lich0821** [comment]
@supermoonie 大佬怎么看

**Comment by supermoonie** [comment]
> @supermoonie 大佬怎么看

嗯。。。我用眼看，这几天我抽时间搞一下

**Comment by joe12801** [comment]
对，支持多个回调地址，这个实用

**Comment by luoqiz** [comment]
@lich0821 这个可以关了

**Comment by lich0821** [comment]
> @lich0821 这个可以关了

是哪个版本实现了？

**Comment by 3CB3EC** [comment]
感觉第一点还是挺重要的，小分辨率下窗口显示不全，而且不能调
虽然最大化窗口以后可以显示全，但是比较不方便
