### ISSUE TITLE
这个是什么错误啊

### ISSUE THREAD

**Issue by bupojie888** [lich0821/wcf-client-rust#4]
执行cargo tauri dev
------------------------------------------
error: failed to run custom build command for `nng-sys v1.4.0-rc.0`

Caused by:
  process didn't exit successfully: `C:\Users\Administrator\Downloads\Compressed\wcf-client-rust-39.0.14.0\wcf-client-rust-39.0.14.0\src-tauri\target\debug\build\nng-sys-cd6ba1e5828f824d\build-script-build` (exit code: 101)
  --- stdout
这个是什么错误啊

**Comment by bupojie888** [comment]
![image](https://github.com/lich0821/wcf-client-rust/assets/75459234/de51d9ca-0812-41a0-b6f1-f47577d97b48)

**Comment by linjiacheng** [comment]
试试安装cmake并放到PATH
