### ISSUE TITLE
WcfRust39.2.4错误

### ISSUE THREAD

**Issue by wjy1630** [lich0821/wcf-client-rust#41]
![mmexport1728527154438](https://github.com/user-attachments/assets/7074823f-91c9-48a8-9c37-ec09249808c7)
WcfRust3.9.2.4 这是啥错误?之前版本没有这个错误啊。

![mmexport1728527693639](https://github.com/user-attachments/assets/63c8ade7-52e6-49bb-8b5d-b27c996334db)
另外这个保存文件接口参数是否有问题？执行错误

**Comment by luoqiz** [comment]
现在改成事件触发机制了，刚点击启动时获取用户信息可能会出现服务还没启动起来，所以显示无法连接，新的pr是显示头像的功能，这个问题也顺带解决了
