### ISSUE TITLE
个人建议和问题

### ISSUE THREAD

**Issue by Gaimoydev** [lich0821/wcf-client-rust#5]
1.添加返回 发送消息人的微信名称（不是wxid）
2.添加api 可以查询群聊所有人的微信名称和wxid
3.添加api 可以查询当前微信下所有群聊的roomid和群聊名称

4.问题 允许好友通过的参数是怎么获取的 比如那个加密的微信名

**Comment by lich0821** [comment]
1、2、3都可以通过查询数据库实现。

4自己尝试一下就知道了。
