### ISSUE TITLE
通过好友申请失败

### ISSUE THREAD

**Issue by JavaZhouQi** [lich0821/wcf-client-rust#55]
accept: {"isSelf":true,"isGroup":true,"id":"4161080899124781480","type":3,"ts":1734937907,"roomid":"51726225966@chatroom","content":"<?xml version=\"1.0\"?>\n<msg>\n\t<img aeskey=\"36d958e95516a89cad50b38fd6f01a18\" encryver=\"1\" cdnthumbaeskey=\"36d958e95516a89cad50b38fd6f01a18\" cdnthumburl=\"3057020100044b304902010002044a263f5402032f57ee02047254f924020467690d33042434346236663461322d333831382d343135632d396465352d346135636233666333373233020401250a020201000405004c4dfe00\" cdnthumblength=\"3856\" cdnthumbheight=\"120\" cdnthumbwidth=\"88\" cdnmidheight=\"0\" cdnmidwidth=\"0\" cdnhdheight=\"0\" cdnhdwidth=\"0\" cdnmidimgurl=\"3057020100044b304902010002044a263f5402032f57ee02047254f924020467690d33042434346236663461322d333831382d343135632d396465352d346135636233666333373233020401250a020201000405004c4dfe00\" length=\"22962\" md5=\"55dc8cb29b18388e6976048178ec7114\" hevc_mid_size=\"22962\" originsourcemd5=\"ab5041189327404dd9102b91bf7e16d7\">\n\t\t<secHashInfoBase64>eyJwaGFzaCI6IjUxMDA1MTAwMDAwMDEwMTAiLCJwZHFIYXNoIjoiMzk4NjQzOTA1YzVhYmM3Y2Ux\nM2U3OTNlMDRkMWM2ZDFjMzgxODc4MTRmMGJjYjQ3ZTNjYmJlMWI5NmE0NzhmYyJ9\n</secHashInfoBase64>\n\t</img>\n\t<platform_signature />\n\t<imgdatahash />\n\t<ImgSourceInfo>\n\t\t<ImgSourceUrl />\n\t\t<BizType>0</BizType>\n\t</ImgSourceInfo>\n</msg>\n","sender":"wxid_7wid1e7zmm2i22","sign":"6a7aba842d887e123a19937c73cc4ef1","thumb":"D:/app/WeChat/data/WeChat Files/wxid_7wid1e7zmm2i22/FileStorage/MsgAttach/068f0228d0aaa5b7c2da1eaaad868cc3/Thumb/2024-12/c64f72e34aacec03c47ee87924a736fe_t.dat","extra":"D:/app/WeChat/data/WeChat Files/wxid_7wid1e7zmm2i22/FileStorage/MsgAttach/068f0228d0aaa5b7c2da1eaaad868cc3/Image/2024-12/c9a69780f5d5583d286101a39a172273.dat","xml":"<msgsource>\n    <alnode>\n        <fr>2</fr>\n    </alnode>\n    <sec_msg_node>\n        <uuid>b61546fec2adf4572ca8cce4b4a24a82_</uuid>\n        <risk-file-flag />\n        <risk-file-md5-list />\n        <alnode>\n            <fr>1</fr>\n        </alnode>\n    </sec_msg_node>\n    <signature>V1_EhQRyzUu|v1_TW+3zbIx</signature>\n    <tmp_node>\n        <publisher-id />\n    </tmp_node>\n</msgsource>\n"}

通过好友申请请求,{"scene":30,"v3":"v3_020b3826fd030100000000004ee80d5c9f77f8000000501ea9a3dba12f95f6b60a0536a1adb662346b7ca82d5124e330710168c7bbf94cde8566f55b827624bb7719a73b26b0a2be9a85f2603abb482bf8b4@stranger","v4":"v4_000b708f0b040000010000000000482e35adda92b646edb06f0d69671000000050ded0b020927e3c97896a09d47e6e9e1e684b88ca6655d9b4d7229b42530483f41b9b9e7512973f195920540a213095a8f4fc76cf81169c76ac026ec3328220be78ba7306a63450b5c9f595c391aeef96c9a3e74ee93e768c19027101faa3a3b6e6b1b0302418fbaa9c8949998150e8c40f3e2c003378a8@stranger"}

通过好友申请响应,{"status":1,"error":"通过好友申请失败: 通过好友申请失败","data":null}

**Comment by lich0821** [comment]
* https://github.com/lich0821/WeChatFerry/issues/200
* https://github.com/lich0821/WeChatRobot/issues/81
