### ISSUE TITLE
微信客户端已经无法使用

### ISSUE THREAD

**Issue by luoluoluo22** [lich0821/wcf-client-rust#6]
![PixPin_2024-04-23_23-13-08](https://github.com/lich0821/wcf-client-rust/assets/24725251/6ff11c32-ddd4-4eab-9502-529a65936d39)
微信客户端已经无法使用，且必须强制更新

**Comment by lich0821** [comment]
<img width="334" alt="image" src="https://github.com/lich0821/wcf-client-rust/assets/87742696/e61db024-8202-493a-9b2f-7a38359e76ee">

**Comment by lich0821** [comment]
还是来[这边](https://github.com/lich0821/WeChatFerry/issues/148)吧。
