### ISSUE TITLE
这边发送图片时有返回200，但是图片并没有被发送出去，用文档中的测试发送图片也是一样没有发送出图片，但是返回200。

### ISSUE THREAD

**Issue by Yumengming0708** [lich0821/wcf-client-rust#7]
之前有安装过WeChatFerry HTTP，是否需要删除
图片路径确定没有问题，本地图片和网络图片都一样发送不出，文本消息可以正常发出
日志：[wcf.txt](https://github.com/lich0821/wcf-client-rust/files/15107880/wcf.txt)

**Comment by lich0821** [comment]
1、只是安装不影响，不同时运行即可。
2、日志上看没有任何错误，一切正常。
**注**：日志包含隐私信息，注意处理一下

**Comment by Yumengming233** [comment]
这边重新安装微信和项目本体都无法发送图片，使用原来WechatFerry HTTP项目可以正常发送图片。服务器系统是win7，有没有可能因为系统的问题？
