### ISSUE TITLE
发送图片 /wcf/send_img   API 用不了

### ISSUE THREAD

**Issue by yhdufei** [lich0821/wcf-client-rust#8]
发送图片 /wcf/send_img   API 用不了。
参数：

{
  "base64": "string",
  "path": "string",
  "receiver": "string"
}

照这个参数调用，就是发送不成功。在本的api测试也不行。其它API都可以。
是要怎么用吖，非常着急。。

**Comment by lich0821** [comment]
我知道你很急，但你先别急。你把ISSUE提到正确的项目去。这不是本项目的接口。
